[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libxcb1", "libxcb-shm0", "libxcb-cursor0", "libxcb-icccm4", "libxcb-keysyms1", "libxcb-render-util0", "libxcb-shape0", "libxcb-xinerama0", "libxcb-xkb1", "libxext6", "libsm6", "libxrender1"]
